double a, b, c, d;
a = 2;
b = 4 ;
c =  (a+b) * b;
d = c * b / (a*a);
a = d / (c+b);
b = b+a;
Console.WriteLine($"A Variavel A vale {a}");
Console.WriteLine($"A Variavel B vale {b}");
Console.WriteLine($"A Variavel C vale {c}");
Console.WriteLine($"A Variavel B vale {d}");
